### ISSUE TITLE
Any plan to upgrade to 3.8?

### ISSUE THREAD

**Issue by kamoljan** [avianey/facebook-api-android-maven#12]

**Comment by chrisjenx** [comment]
Well we're at 3.14 now... if that could be bumped that would be great

**Comment by jondwillis** [comment]
:+1:

**Comment by kwent** [comment]
:+1:

**Comment by avianey** [comment]
I'll do it on saturday...

**Comment by avianey** [comment]
done!

**Comment by istipen** [comment]
I'm receiving this warning (and 50+ more) after the 3.14 update..
Warning:com.facebook.FacebookAppLinkResolver: can't find superclass or interface bolts.AppLinkResolver

then proguard fails...

Am i missing additional changes to build.gradle or proguard config files?

**Comment by avianey** [comment]
You might have forgotten to reference the new Bolts dependency as input jar (-injars or -libraryjars) in the proguard config file (see : http://proguard.sourceforge.net/index.html#manual/troubleshooting.html)

**Comment by istipen** [comment]
:+1:
