### ISSUE TITLE
Old support-v4 library conflicts with other libraries

### ISSUE THREAD

**Issue by gaudecker** [avianey/facebook-api-android-maven#13]
It seems this library uses `com.google.android:support-v4:r7`, other libraries I'm using use `com.android.support:support-v4:19.+`

Because of this, I'm unable to build my project, thus getting the `Multiple dex file define` error.

**Comment by jelmervisser** [comment]
In the README:

configurations.all {
  exclude group: 'com.google.android', module: 'support-v4', version: 'r7'
  // other configurations
}

**Comment by avianey** [comment]
:+1: 
@jelmertjuh thankyou for quoting the doc
