### ISSUE TITLE
Request for 3.16.0

### ISSUE THREAD

**Issue by MariusVolkhart** [avianey/facebook-api-android-maven#16]
Version 3.16 was released on July 18th, and I'd kindly like to request a port for it.

**Comment by avianey** [comment]
done!
should be available in Maven central repo within 2 hours...
regards

**Comment by sschuberth** [comment]
Thanks for this, too. But shouldn't the README be updated then, too? In both the master and v3.16.0-fix branches it still says "Current port is based on the v3.15.0 available at ...".
