### ISSUE TITLE
Please release facebook api version v3.20.0

### ISSUE THREAD

**Issue by anti43** [avianey/facebook-api-android-maven#18]
..3.18 became unusable when they disabled sslv3

**Comment by avianey** [comment]
use the official one : https://github.com/facebook/facebook-android-sdk
this one will not be updated.

**Comment by anti43** [comment]
hm the official one has no maven integration :)

**Comment by avianey** [comment]
it has, since late september...

**Comment by anti43** [comment]
for the record:

compile 'com.facebook.android:facebook-android-sdk:3.20.0'
