### ISSUE TITLE
no repository found

### ISSUE THREAD

**Issue by vincenzovitale** [avianey/facebook-api-android-maven#3]
no repository here:
http://avianey.github.com/facebook-api-android-maven/

**Comment by avianey** [comment]
use the new github.io domain http://avianey.github.io/facebook-api-android-maven/

**Comment by vincenzovitale** [comment]
sorry,
I meant to copy and paste that one, but nothing is there (404)

**Comment by avianey** [comment]
It should work as the necessary files are available here :

http://avianey.github.io/facebook-api-android-maven/com/github/avianey/facebook-android-api/3.0.1/facebook-android-api-3.0.1.apklib
http://avianey.github.io/facebook-api-android-maven/com/github/avianey/facebook-android-api/3.0.1/facebook-android-api-3.0.1.pom

**Comment by vincenzovitale** [comment]
then sorry for that, I tought was possible to navigate the repository.

thanks for the project,
V.
