### ISSUE TITLE
dependency address + clarification

### ISSUE THREAD

**Issue by ticofab** [avianey/facebook-api-android-maven#5]
Hi, and thanks for your work.

At first I couldn't resolve the dependency, but then I noticed that the pom.xml file is in the /facebook subdir. By using 

<url>http://avianey.github.io/facebook-api-android-maven/facebook/</url>

(appending /facebook to your indication) it builds fine and Eclipse gives no errors.

Yet at this point I am not able to use it as Eclipse can't find com.facebook.\* .
Is there anything more I need to do?

Thanks for your help

**Comment by avianey** [comment]
Hi, this is a simple, non browsable directory...
You can access the pom here : 

http://avianey.github.io/facebook-api-android-maven/com/github/avianey/facebook-android-api/3.0.1/facebook-android-api-3.0.1.pom

as the groupId is com.github.avianey, the artifactId is facebook-android-api and the version is 3.0.1 maven should fetch this URL too and everything should work fine!!!

why would you use /facebook at the end ?
